# Generated by Django 2.2.1 on 2019-05-25 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '标签管理',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='专题名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('desc', models.TextField(blank=True, max_length=300, null=True, verbose_name='专题描述')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '专题管理',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
                ('desc', models.TextField(max_length=200, verbose_name='分类描述')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '博客分类',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('slug', models.SlugField(blank=True, help_text='链接后缀，必须为英文字符', max_length=100, null=True, verbose_name='slug')),
                ('picture', models.ImageField(blank=True, default='images/timg.jpg', max_length=200, null=True, upload_to='images/', verbose_name='封面图')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('has_pub', models.PositiveSmallIntegerField(choices=[(0, '发布'), (1, '存草稿')], default=0, verbose_name='是否发布')),
                ('has_reprint', models.PositiveSmallIntegerField(choices=[(0, '原创'), (1, '转载')], default=0, verbose_name='是否原创')),
                ('has_url', models.URLField(blank=True, null=True, verbose_name='原文链接')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Topic', verbose_name='专题')),
            ],
            options={
                'verbose_name_plural': '文章管理',
                'ordering': ['-pub_date'],
            },
        ),
    ]
