# Generated by Django 2.2.1 on 2019-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/', verbose_name='封面图'),
        ),
    ]
