# Generated by Django 2.2.1 on 2019-05-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190529_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_nums',
        ),
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_nums', models.IntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article')),
            ],
        ),
    ]
