# Generated by Django 2.2.1 on 2019-05-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190529_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
